name: build
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        env: 
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in the repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      
      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      # - name: Lint Ruby / Rails
      #   run: bundle exec rubocop

      - name: Build and run tests
        env:
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails app:db:prepare
          bundle exec rails test

      - name: Notify Teams
        uses: toko-bifrost/ms-teams-deploy-card@master
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
